version: '3.4'

services:

  gamenews.webapi:
    image: ${DOCKER_REGISTRY-}gamenews
    build:
      context: .
      dockerfile: src/GameNews.WebApi/Dockerfile
    depends_on:
        - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - SA_PASSWORD=Oksan@2003 
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

volumes:
    db: